# Generated by cucumber-sinatra. (2013-09-03 21:25:47 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/overlook.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Torrance

class TorranceWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TorranceWorld.new
end
