language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: YrJ0Mt6yu8+1wm0p9IvACcMUIaCtdWXk7upn0HhWeHkcjdPUVle0nkSZsafR1JybQz8IgdeRS1urCKE0C02Yy6hBeJf1OwiHtRh8z8Pv79Dvv8U1cLun7hRhV3i9N/yGuXy+1yyhBhp1nO9JMecAks3wH2xaYXh9x2ic8q63mwU=
  app: sheltered-cliffs-2386
